repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
        exclude: django_ace/static/django_ace/ace/
      - id: end-of-file-fixer
        exclude: django_ace/static/django_ace/ace/
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        exclude: django_ace/static/django_ace/ace/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: django_ace/static/django_ace/ace/
